#assume this is autopopulated
BusinessUnit:
    P&O: "#FF6600"
    RBB: "#66CC00"
    WIB: "#FFCC00"
    CORP: "#6666CC"
    TECH: "#3399FF"
    BT: "#009999"
    SIP: "#CCCCCC"
    Other: "#FF66FF"
MoveType:
    MOVE: /images/arrow_switch.png
    SIZE: /images/arrow_out.png	
    WRKS: /images/cog.png
    SIP: /images/briefcase.png
OpportunityStatus:
    Opportunity: /images/lightbulb_off.png
    Qualified: /images/lightbulb.png
    Planning: /images/calendar.png
    Agreed: /images/thumb_up.png
    Delivered: /images/tick.png
    Cancelled: /images/cancel.png
BuildingZone:
    CBD: "#3399FF"
    Metro: "#66CC00"
StandardIcon:
    Edit: /images/pencil.png
    Add: /images/table_add.png
    Person: /images/user_suit.png
    Show: /images/table_go.png
    Destroy: /images/table_delete.png
    Zone: /images/map.png
    SIP: /images/briefcase.png
    YesIcon: /images/accept.png
    NoIcon: /images/cross.png
    Date: /images/calendar_view_day.png
StandardColour:
    TableRow: "#D5E8FF"
State:
    NSW: New South Wales
    QLD: Queensland
    VIC: Victoria
    WA: Western Australia
    SA: South Australia
    TAS: Tasmania
    NT: Northern Territory
    ACT: Australian Capital Territory
